<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConfectionarySeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    // Seed confections table
    $confections = array(
      array('id' => 1, 'cname' => 'Süni', 'type' => 'mixed', 'prizewinning' => 0),
      array('id' => 2, 'cname' => 'Gesztenyealagút', 'type' => 'mixed', 'prizewinning' => 0),
      array('id' => 3, 'cname' => 'Sajtos pogácsa', 'type' => 'salty biscuit', 'prizewinning' => 0),
      array('id' => 4, 'cname' => 'Diós-mákos', 'type' => 'roll', 'prizewinning' => 0),
      array('id' => 5, 'cname' => 'Sajttorta (málnás)', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 6, 'cname' => 'Citrom', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 7, 'cname' => 'Eszterházy', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 8, 'cname' => 'Rákóczi-túrós', 'type' => 'pie', 'prizewinning' => 0),
      array('id' => 9, 'cname' => 'Meggyes kocka', 'type' => 'creamy cake', 'prizewinning' => 0),
      array('id' => 10, 'cname' => 'Legényfogó', 'type' => 'cake', 'prizewinning' => -1),
      array('id' => 11, 'cname' => 'Alpesi karamell', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 12, 'cname' => 'Kókuszcsók', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 13, 'cname' => 'Habos mákos', 'type' => 'pie', 'prizewinning' => 0),
      array('id' => 14, 'cname' => 'Szilvás', 'type' => 'pie', 'prizewinning' => 0),
      array('id' => 15, 'cname' => 'Juhtúrós párna', 'type' => 'salty biscuit', 'prizewinning' => 0),
      array('id' => 16, 'cname' => 'Mákos guba', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 17, 'cname' => 'Néró', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 18, 'cname' => 'Sacher', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 19, 'cname' => 'Citrom', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 20, 'cname' => 'Ribizlihabos-almás réteges', 'type' => 'special cake', 'prizewinning' => -1),
      array('id' => 21, 'cname' => 'Három kívánság', 'type' => 'cake', 'prizewinning' => -1),
      array('id' => 22, 'cname' => 'Dobos', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 23, 'cname' => 'Epres mascarpone', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 24, 'cname' => 'Csokoládémousse', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 25, 'cname' => 'Oroszkrém', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 26, 'cname' => 'Medvetalp', 'type' => 'mixed', 'prizewinning' => 0),
      array('id' => 27, 'cname' => 'Trüffel', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 28, 'cname' => 'Tejszínes gyümölcsös (meggy)', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 29, 'cname' => 'Mákos-szilvalekváros', 'type' => 'roll', 'prizewinning' => 0),
      array('id' => 30, 'cname' => 'Ribizlihabos-﻿almá﻿s réteges tortaszelet', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 31, 'cname' => 'Marcipános vágott', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 32, 'cname' => 'Indiáner', 'type' => 'mixed', 'prizewinning' => 0),
      array('id' => 33, 'cname' => 'Meggyes', 'type' => 'pie', 'prizewinning' => 0),
      array('id' => 34, 'cname' => 'Mákos', 'type' => 'roll', 'prizewinning' => 0),
      array('id' => 35, 'cname' => 'Sós karamella', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 36, 'cname' => 'Legényfogó', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 37, 'cname' => 'Rigó Jancsi', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 38, 'cname' => 'Tejszínes gyümölcsös (erdei gyümölcs)', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 39, 'cname' => 'Ez+Az (csokoládé és gesztenye)', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 40, 'cname' => 'Málnás mascarpone', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 41, 'cname' => 'Dobos', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 42, 'cname' => 'Ferrero', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 43, 'cname' => 'Vegyes házi pitefalatok', 'type' => 'pie', 'prizewinning' => 0),
      array('id' => 44, 'cname' => 'Ökörszem', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 45, 'cname' => 'Danubius kocka', 'type' => 'creamy cake', 'prizewinning' => 0),
      array('id' => 46, 'cname' => 'Sajtkrémmel töltött fánkocska', 'type' => 'salty biscuit', 'prizewinning' => 0),
      array('id' => 47, 'cname' => 'Túrókrém gyümölccsel díszítve', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 48, 'cname' => 'Almás', 'type' => 'pie', 'prizewinning' => 0),
      array('id' => 49, 'cname' => 'Mignon', 'type' => 'mixed', 'prizewinning' => 0),
      array('id' => 50, 'cname' => 'Csokoládémousse fényes csokoládéval', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 51, 'cname' => 'Vágott sós (sós omlós)', 'type' => 'salty biscuit', 'prizewinning' => 0),
      array('id' => 52, 'cname' => 'Nagyi sós', 'type' => 'salty biscuit', 'prizewinning' => 0),
      array('id' => 53, 'cname' => 'Vegyes sós', 'type' => 'salty biscuit', 'prizewinning' => 0),
      array('id' => 54, 'cname' => 'Somlói', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 55, 'cname' => 'Tiramisu', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 56, 'cname' => 'Hegyvidék', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 57, 'cname' => 'Szedres csokoládé', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 58, 'cname' => 'Pogácsák mixeden', 'type' => 'salty biscuit', 'prizewinning' => 0),
      array('id' => 59, 'cname' => 'Lúdláb', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 60, 'cname' => 'Sacher', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 61, 'cname' => 'Eszterházy', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 62, 'cname' => 'Zalavári gesztenye', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 63, 'cname' => 'Gesztenyegolyó', 'type' => 'mixed', 'prizewinning' => 0),
      array('id' => 64, 'cname' => 'Pisztáciás-málnás mascarpone', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 65, 'cname' => 'Habos mákos', 'type' => 'mixed', 'prizewinning' => 0),
      array('id' => 66, 'cname' => 'Franciakrémes', 'type' => 'pastry', 'prizewinning' => 0),
      array('id' => 67, 'cname' => 'Gesztenye kocka', 'type' => 'creamy cake', 'prizewinning' => 0),
      array('id' => 68, 'cname' => 'Pisztáciás-málnás mascarpone', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 69, 'cname' => 'Málnás kocka', 'type' => 'creamy cake', 'prizewinning' => 0),
      array('id' => 70, 'cname' => 'Sajttorta (málnás)', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 71, 'cname' => 'Túrókrém gyümölccsel', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 72, 'cname' => 'Csokis kaland', 'type' => 'special cake', 'prizewinning' => -1),
      array('id' => 73, 'cname' => 'Somlói', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 74, 'cname' => 'Palermo', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 75, 'cname' => 'Szilvalekváros', 'type' => 'roll', 'prizewinning' => 0),
      array('id' => 76, 'cname' => 'Ünnepi diótorta grillázzsal', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 77, 'cname' => 'Oroszkrém', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 78, 'cname' => 'Mini zserbó', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 79, 'cname' => 'Sajtos masni', 'type' => 'salty biscuit', 'prizewinning' => 0),
      array('id' => 80, 'cname' => 'Zserbó', 'type' => 'pie', 'prizewinning' => 0),
      array('id' => 81, 'cname' => 'Tejszínes gyümölcsös (málna)', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 82, 'cname' => 'Marcipános csokoládé', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 83, 'cname' => 'Csokis kaland', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 84, 'cname' => 'Marcipán tekercs', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 85, 'cname' => 'Képviselőfánk', 'type' => 'mixed', 'prizewinning' => 0),
      array('id' => 86, 'cname' => 'Epres omlett', 'type' => 'mixed', 'prizewinning' => 0),
      array('id' => 87, 'cname' => 'Mini linzer', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 88, 'cname' => 'Linzerkarika', 'type' => 'mixed', 'prizewinning' => 0),
      array('id' => 89, 'cname' => 'Szedres csokoládé', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 90, 'cname' => 'Narancsív', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 91, 'cname' => 'Gesztenyepüré', 'type' => 'mixed', 'prizewinning' => 0),
      array('id' => 92, 'cname' => 'Palermo', 'type' => 'creamy cake', 'prizewinning' => 0),
      array('id' => 93, 'cname' => 'Csokis néró', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 94, 'cname' => 'Flódni', 'type' => 'pie', 'prizewinning' => 0),
      array('id' => 95, 'cname' => 'Mézeskalács', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 96, 'cname' => 'Olívás pogácsa', 'type' => 'salty biscuit', 'prizewinning' => 0),
      array('id' => 97, 'cname' => 'Florentin', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 98, 'cname' => 'Tiramisu', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 99, 'cname' => 'Zoli kedvence (vágott édes tea)', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 100, 'cname' => 'Erdei gyümölcs kocka', 'type' => 'creamy cake', 'prizewinning' => 0),
      array('id' => 101, 'cname' => 'Rákóczi-túrós', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 102, 'cname' => 'Mézeskrémes', 'type' => 'pie', 'prizewinning' => 0),
      array('id' => 103, 'cname' => 'Trüffel', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 104, 'cname' => 'Szilvás papucs', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 105, 'cname' => 'Zalavári gesztenye', 'type' => 'cake', 'prizewinning' => -1),
      array('id' => 106, 'cname' => 'Danubius', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 107, 'cname' => 'Alpesi karamell', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 108, 'cname' => 'Puncs', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 109, 'cname' => 'Gesztenye szív', 'type' => 'mixed', 'prizewinning' => 0),
      array('id' => 110, 'cname' => 'Ez+Az (csokoládé és gesztenye)', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 111, 'cname' => 'Tökmagos félhold', 'type' => 'salty biscuit', 'prizewinning' => 0),
      array('id' => 112, 'cname' => 'Burgonyás pogácsa', 'type' => 'salty biscuit', 'prizewinning' => 0),
      array('id' => 113, 'cname' => 'Somlói galuska', 'type' => 'mixed', 'prizewinning' => 0),
      array('id' => 114, 'cname' => 'Puncs', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 115, 'cname' => 'Lekváros vágott', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 116, 'cname' => 'Oreo', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 117, 'cname' => 'Vintage', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 118, 'cname' => 'Rigó Jancsi', 'type' => 'creamy cake', 'prizewinning' => 0),
      array('id' => 119, 'cname' => 'Feketeerdő', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 120, 'cname' => 'Kókuszos vágott', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 121, 'cname' => 'Feketeerdő', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 122, 'cname' => 'Moscauer', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 123, 'cname' => 'Diós', 'type' => 'roll', 'prizewinning' => 0),
      array('id' => 124, 'cname' => 'Rákóczi-túrós', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 125, 'cname' => 'Három kívánság', 'type' => 'special cake', 'prizewinning' => 0),
      array('id' => 126, 'cname' => 'Gesztenyés-karamellás', 'type' => 'roll', 'prizewinning' => 0),
      array('id' => 127, 'cname' => 'Gesztenyés szív', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 128, 'cname' => 'Ropi', 'type' => 'salty biscuit', 'prizewinning' => 0),
      array('id' => 129, 'cname' => 'Paleolit étcsokoládé', 'type' => 'special cake', 'prizewinning' => 0),
      array('id' => 130, 'cname' => 'Túrós', 'type' => 'pie', 'prizewinning' => 0),
      array('id' => 131, 'cname' => 'Ischler', 'type' => 'mixed', 'prizewinning' => 0),
      array('id' => 132, 'cname' => 'Lúdláb', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 133, 'cname' => 'Csokoládémousse', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 134, 'cname' => 'Dió', 'type' => 'cake', 'prizewinning' => 0),
      array('id' => 135, 'cname' => 'Krémes', 'type' => 'pastry', 'prizewinning' => 0),
      array('id' => 136, 'cname' => 'Mini ischler', 'type' => 'sweet biscuit', 'prizewinning' => 0),
      array('id' => 137, 'cname' => 'Paleolit étcsokoládé', 'type' => 'cake slice', 'prizewinning' => 0),
      array('id' => 138, 'cname' => 'Tejfölös túrós hajtogatott', 'type' => 'salty biscuit', 'prizewinning' => 0),
      array('id' => 139, 'cname' => 'Mákos guba', 'type' => 'cake', 'prizewinning' => 0)
    );

    foreach ($confections as $confection) {
      DB::table('confections')->insert($confection);
    }

    // Seed contents table
    $contents =    array(
      array('id' => 1, 'confid' => 26, 'free' => 'G'),
      array('id' => 2, 'confid' => 37, 'free' => 'L'),
      array('id' => 3, 'confid' => 83, 'free' => 'HC'),
      array('id' => 4, 'confid' => 91, 'free' => 'G'),
      array('id' => 5, 'confid' => 137, 'free' => 'G'),
      array('id' => 6, 'confid' => 60, 'free' => 'Te'),
      array('id' => 7, 'confid' => 129, 'free' => 'HC'),
      array('id' => 8, 'confid' => 122, 'free' => 'To'),
      array('id' => 9, 'confid' => 90, 'free' => 'G'),
      array('id' => 10, 'confid' => 26, 'free' => 'To'),
      array('id' => 11, 'confid' => 94, 'free' => 'L'),
      array('id' => 12, 'confid' => 46, 'free' => 'É'),
      array('id' => 13, 'confid' => 72, 'free' => 'HC'),
      array('id' => 14, 'confid' => 114, 'free' => 'Te'),
      array('id' => 15, 'confid' => 63, 'free' => 'To'),
      array('id' => 16, 'confid' => 12, 'free' => 'Te'),
      array('id' => 17, 'confid' => 128, 'free' => 'É'),
      array('id' => 18, 'confid' => 51, 'free' => 'É'),
      array('id' => 19, 'confid' => 109, 'free' => 'To'),
      array('id' => 20, 'confid' => 109, 'free' => 'G'),
      array('id' => 21, 'confid' => 97, 'free' => 'G'),
      array('id' => 22, 'confid' => 97, 'free' => 'To'),
      array('id' => 23, 'confid' => 24, 'free' => 'L'),
      array('id' => 24, 'confid' => 91, 'free' => 'To'),
      array('id' => 25, 'confid' => 137, 'free' => 'L'),
      array('id' => 26, 'confid' => 84, 'free' => 'G'),
      array('id' => 27, 'confid' => 30, 'free' => 'HC'),
      array('id' => 28, 'confid' => 108, 'free' => 'Te'),
      array('id' => 29, 'confid' => 84, 'free' => 'To'),
      array('id' => 30, 'confid' => 6, 'free' => 'L'),
      array('id' => 31, 'confid' => 108, 'free' => 'L'),
      array('id' => 32, 'confid' => 12, 'free' => 'L'),
      array('id' => 33, 'confid' => 79, 'free' => 'É'),
      array('id' => 34, 'confid' => 72, 'free' => 'G'),
      array('id' => 35, 'confid' => 118, 'free' => 'L'),
      array('id' => 36, 'confid' => 60, 'free' => 'L'),
      array('id' => 37, 'confid' => 52, 'free' => 'É'),
      array('id' => 38, 'confid' => 137, 'free' => 'HC'),
      array('id' => 39, 'confid' => 114, 'free' => 'L'),
      array('id' => 40, 'confid' => 90, 'free' => 'To'),
      array('id' => 41, 'confid' => 20, 'free' => 'HC'),
      array('id' => 42, 'confid' => 63, 'free' => 'G'),
      array('id' => 43, 'confid' => 129, 'free' => 'G'),
      array('id' => 44, 'confid' => 129, 'free' => 'L'),
      array('id' => 45, 'confid' => 15, 'free' => 'É')
    );

    foreach ($contents as $content) {
      DB::table('contents')->insert($content);
    }

    // Seed prices table
    $prices = array(
      array('id' => 1, 'confid' => 32, 'price' => 500, 'unit' => 'pce'),
      array('id' => 2, 'confid' => 76, 'price' => 10900, 'unit' => '16 slices'),
      array('id' => 3, 'confid' => 106, 'price' => 4300, 'unit' => '8 slices'),
      array('id' => 4, 'confid' => 88, 'price' => 300, 'unit' => 'pce'),
      array('id' => 5, 'confid' => 116, 'price' => 16200, 'unit' => '24 slices'),
      array('id' => 6, 'confid' => 135, 'price' => 250, 'unit' => 'pce'),
      array('id' => 7, 'confid' => 127, 'price' => 4400, 'unit' => 'kg'),
      array('id' => 8, 'confid' => 50, 'price' => 13400, 'unit' => '24 slices'),
      array('id' => 9, 'confid' => 70, 'price' => 700, 'unit' => 'pce'),
      array('id' => 10, 'confid' => 31, 'price' => 5200, 'unit' => 'kg'),
      array('id' => 11, 'confid' => 96, 'price' => 3300, 'unit' => 'kg ​​'),
      array('id' => 12, 'confid' => 116, 'price' => 5700, 'unit' => '8 slices'),
      array('id' => 13, 'confid' => 22, 'price' => 9000, 'unit' => '16 slices'),
      array('id' => 14, 'confid' => 138, 'price' => 4400, 'unit' => 'kg'),
      array('id' => 15, 'confid' => 112, 'price' => 2900, 'unit' => 'kg'),
      array('id' => 16, 'confid' => 58, 'price' => 3200, 'unit' => 'kg'),
      array('id' => 17, 'confid' => 98, 'price' => 10400, 'unit' => '16 slices'),
      array('id' => 18, 'confid' => 75, 'price' => 2100, 'unit' => 'bar'),
      array('id' => 19, 'confid' => 24, 'price' => 11400, 'unit' => '24 slices'),
      array('id' => 20, 'confid' => 62, 'price' => 600, 'unit' => 'pce'),
      array('id' => 21, 'confid' => 61, 'price' => 8400, 'unit' => '16 slices'),
      array('id' => 22, 'confid' => 105, 'price' => 10900, 'unit' => '16 slices'),
      array('id' => 23, 'confid' => 20, 'price' => 4700, 'unit' => '8 slices'),
      array('id' => 24, 'confid' => 123, 'price' => 1800, 'unit' => 'bar'),
      array('id' => 25, 'confid' => 60, 'price' => 8200, 'unit' => '16 slices'),
      array('id' => 26, 'confid' => 24, 'price' => 3900, 'unit' => '8 slices'),
      array('id' => 27, 'confid' => 38, 'price' => 4300, 'unit' => '8 slices'),
      array('id' => 28, 'confid' => 126, 'price' => 2100, 'unit' => 'bar'),
      array('id' => 29, 'confid' => 64, 'price' => 750, 'unit' => 'pce'),
      array('id' => 30, 'confid' => 109, 'price' => 300, 'unit' => 'pce'),
      array('id' => 32, 'confid' => 89, 'price' => 13200, 'unit' => '24 slices'),
      array('id' => 33, 'confid' => 98, 'price' => 15400, 'unit' => '24 slices'),
      array('id' => 34, 'confid' => 24, 'price' => 7400, 'unit' => '16 slices'),
      array('id' => 35, 'confid' => 76, 'price' => 5700, 'unit' => '8 slices'),
      array('id' => 36, 'confid' => 131, 'price' => 250, 'unit' => 'pce'),
      array('id' => 37, 'confid' => 50, 'price' => 9200, 'unit' => '16 slices'),
      array('id' => 38, 'confid' => 55, 'price' => 600, 'unit' => 'pce'),
      array('id' => 39, 'confid' => 87, 'price' => 3400, 'unit' => 'kg'),
      array('id' => 40, 'confid' => 4, 'price' => 3500, 'unit' => 'wreath'),
      array('id' => 41, 'confid' => 8, 'price' => 400, 'unit' => 'pce'),
      array('id' => 42, 'confid' => 100, 'price' => 450, 'unit' => 'pce'),
      array('id' => 43, 'confid' => 129, 'price' => 5300, 'unit' => '8 slices'),
      array('id' => 44, 'confid' => 35, 'price' => 4700, 'unit' => '8 slices'),
      array('id' => 45, 'confid' => 47, 'price' => 490, 'unit' => 'pce'),
      array('id' => 46, 'confid' => 89, 'price' => 9000, 'unit' => '16 slices'),
      array('id' => 47, 'confid' => 111, 'price' => 3300, 'unit' => 'kg'),
      array('id' => 48, 'confid' => 94, 'price' => 400, 'unit' => 'pce'),
      array('id' => 49, 'confid' => 42, 'price' => 16200, 'unit' => '24 slices'),
      array('id' => 50, 'confid' => 80, 'price' => 350, 'unit' => 'pce'),
      array('id' => 51, 'confid' => 134, 'price' => 4700, 'unit' => '8 slices'),
      array('id' => 52, 'confid' => 128, 'price' => 4000, 'unit' => 'kg'),
      array('id' => 53, 'confid' => 90, 'price' => 5200, 'unit' => 'kg'),
      array('id' => 54, 'confid' => 39, 'price' => 13200, 'unit' => '24 slices'),
      array('id' => 55, 'confid' => 71, 'price' => 7400, 'unit' => '16 slices'),
      array('id' => 56, 'confid' => 17, 'price' => 3400, 'unit' => 'kg'),
      array('id' => 57, 'confid' => 68, 'price' => 18400, 'unit' => '24 slices'),
      array('id' => 58, 'confid' => 81, 'price' => 8200, 'unit' => '16 slices'),
      array('id' => 59, 'confid' => 134, 'price' => 9000, 'unit' => '16 slices'),
      array('id' => 60, 'confid' => 108, 'price' => 11400, 'unit' => '24 slices'),
      array('id' => 61, 'confid' => 97, 'price' => 5200, 'unit' => 'kg'),
      array('id' => 62, 'confid' => 81, 'price' => 4300, 'unit' => '8 slices'),
      array('id' => 63, 'confid' => 44, 'price' => 3800, 'unit' => 'kg'),
      array('id' => 64, 'confid' => 72, 'price' => 5700, 'unit' => '8 slices'),
      array('id' => 65, 'confid' => 49, 'price' => 250, 'unit' => 'pce'),
      array('id' => 66, 'confid' => 48, 'price' => 350, 'unit' => 'pce'),
      array('id' => 67, 'confid' => 14, 'price' => 350, 'unit' => 'pce'),
      array('id' => 68, 'confid' => 107, 'price' => 12200, 'unit' => '24 slices'),
      array('id' => 69, 'confid' => 27, 'price' => 15400, 'unit' => '24 slices'),
      array('id' => 70, 'confid' => 106, 'price' => 12100, 'unit' => '24 slices'),
      array('id' => 71, 'confid' => 74, 'price' => 7400, 'unit' => '16 slices'),
      array('id' => 72, 'confid' => 40, 'price' => 5700, 'unit' => '8 slices'),
      array('id' => 73, 'confid' => 133, 'price' => 450, 'unit' => 'pce'),
      array('id' => 74, 'confid' => 77, 'price' => 490, 'unit' => 'pce'),
      array('id' => 75, 'confid' => 22, 'price' => 13200, 'unit' => '24 slices'),
      array('id' => 76, 'confid' => 119, 'price' => 9000, 'unit' => '16 slices'),
      array('id' => 77, 'confid' => 120, 'price' => 3400, 'unit' => 'kg'),
      array('id' => 78, 'confid' => 105, 'price' => 5700, 'unit' => '8 slices'),
      array('id' => 79, 'confid' => 119, 'price' => 13200, 'unit' => '24 slices'),
      array('id' => 80, 'confid' => 99, 'price' => 4600, 'unit' => 'kg'),
      array('id' => 81, 'confid' => 61, 'price' => 12200, 'unit' => '24 slices'),
      array('id' => 82, 'confid' => 93, 'price' => 4200, 'unit' => 'kg'),
      array('id' => 83, 'confid' => 59, 'price' => 13200, 'unit' => '24 slices'),
      array('id' => 84, 'confid' => 82, 'price' => 5700, 'unit' => '8 slices'),
      array('id' => 85, 'confid' => 56, 'price' => 600, 'unit' => 'pce'),
      array('id' => 86, 'confid' => 23, 'price' => 550, 'unit' => 'pce'),
      array('id' => 87, 'confid' => 81, 'price' => 12100, 'unit' => '24 slices'),
      array('id' => 88, 'confid' => 67, 'price' => 500, 'unit' => 'pce'),
      array('id' => 89, 'confid' => 68, 'price' => 6400, 'unit' => '8 slices'),
      array('id' => 90, 'confid' => 38, 'price' => 8200, 'unit' => '16 slices'),
      array('id' => 91, 'confid' => 139, 'price' => 4700, 'unit' => '8 slices'),
      array('id' => 92, 'confid' => 30, 'price' => 530, 'unit' => 'pce'),
      array('id' => 93, 'confid' => 95, 'price' => 16200, 'unit' => '24 slices'),
      array('id' => 94, 'confid' => 101, 'price' => 400, 'unit' => 'pce'),
      array('id' => 95, 'confid' => 65, 'price' => 400, 'unit' => 'pce'),
      array('id' => 96, 'confid' => 10, 'price' => 12100, 'unit' => '24 slices'),
      array('id' => 97, 'confid' => 59, 'price' => 9000, 'unit' => '16 slices'),
      array('id' => 98, 'confid' => 119, 'price' => 4700, 'unit' => '8 slices'),
      array('id' => 99, 'confid' => 82, 'price' => 16200, 'unit' => '24 slices'),
      array('id' => 100, 'confid' => 3, 'price' => 3300, 'unit' => 'kg'),
      array('id' => 101, 'confid' => 104, 'price' => 4200, 'unit' => 'kg'),
      array('id' => 102, 'confid' => 110, 'price' => 530, 'unit' => 'pce'),
      array('id' => 103, 'confid' => 1, 'price' => 300, 'unit' => 'pce'),
      array('id' => 104, 'confid' => 25, 'price' => 8200, 'unit' => '16 slices'),
      array('id' => 105, 'confid' => 40, 'price' => 16200, 'unit' => '24 slices'),
      array('id' => 106, 'confid' => 36, 'price' => 490, 'unit' => 'pce'),
      array('id' => 107, 'confid' => 124, 'price' => 3900, 'unit' => '8 slices'),
      array('id' => 108, 'confid' => 16, 'price' => 530, 'unit' => 'pce'),
      array('id' => 109, 'confid' => 29, 'price' => 3500, 'unit' => 'wreath'),
      array('id' => 110, 'confid' => 116, 'price' => 10900, 'unit' => '16 slices'),
      array('id' => 111, 'confid' => 71, 'price' => 3900, 'unit' => '8 slices'),
      array('id' => 112, 'confid' => 2, 'price' => 500, 'unit' => 'pce'),
      array('id' => 113, 'confid' => 71, 'price' => 11400, 'unit' => '24 slices'),
      array('id' => 114, 'confid' => 10, 'price' => 4300, 'unit' => '8 slices'),
      array('id' => 115, 'confid' => 108, 'price' => 3900, 'unit' => '8 slices'),
      array('id' => 116, 'confid' => 69, 'price' => 450, 'unit' => 'pce'),
      array('id' => 117, 'confid' => 39, 'price' => 9000, 'unit' => '16 slices'),
      array('id' => 118, 'confid' => 25, 'price' => 4300, 'unit' => '8 slices'),
      array('id' => 119, 'confid' => 107, 'price' => 8400, 'unit' => '16 slices'),
      array('id' => 120, 'confid' => 5, 'price' => 9000, 'unit' => '12 slices'),
      array('id' => 121, 'confid' => 106, 'price' => 8200, 'unit' => '16 slices'),
      array('id' => 122, 'confid' => 114, 'price' => 450, 'unit' => 'pce'),
      array('id' => 123, 'confid' => 26, 'price' => 400, 'unit' => 'pce'),
      array('id' => 124, 'confid' => 82, 'price' => 10900, 'unit' => '16 slices'),
      array('id' => 125, 'confid' => 28, 'price' => 8200, 'unit' => '16 slices'),
      array('id' => 126, 'confid' => 42, 'price' => 10900, 'unit' => '16 slices'),
      array('id' => 127, 'confid' => 35, 'price' => 13200, 'unit' => '24 slices'),
      array('id' => 128, 'confid' => 74, 'price' => 3900, 'unit' => '8 slices'),
      array('id' => 129, 'confid' => 19, 'price' => 450, 'unit' => 'pce'),
      array('id' => 130, 'confid' => 25, 'price' => 12100, 'unit' => '24 slices'),
      array('id' => 131, 'confid' => 125, 'price' => 5700, 'unit' => '8 slices'),
      array('id' => 132, 'confid' => 95, 'price' => 5700, 'unit' => '8 slices'),
      array('id' => 133, 'confid' => 34, 'price' => 1700, 'unit' => 'bar'),
      array('id' => 134, 'confid' => 121, 'price' => 530, 'unit' => 'pce'),
      array('id' => 135, 'confid' => 76, 'price' => 16200, 'unit' => '24 slices'),
      array('id' => 136, 'confid' => 13, 'price' => 400, 'unit' => 'pce'),
      array('id' => 137, 'confid' => 60, 'price' => 12100, 'unit' => '24 slices'),
      array('id' => 138, 'confid' => 33, 'price' => 350, 'unit' => 'pce'),
      array('id' => 139, 'confid' => 132, 'price' => 530, 'unit' => 'pce'),
      array('id' => 140, 'confid' => 117, 'price' => 9900, 'unit' => '16 slices'),
      array('id' => 141, 'confid' => 27, 'price' => 10400, 'unit' => '16 slices'),
      array('id' => 142, 'confid' => 18, 'price' => 490, 'unit' => 'pce'),
      array('id' => 143, 'confid' => 124, 'price' => 7400, 'unit' => '16 slices'),
      array('id' => 144, 'confid' => 122, 'price' => 5200, 'unit' => 'kg'),
      array('id' => 145, 'confid' => 59, 'price' => 4700, 'unit' => '8 slices'),
      array('id' => 146, 'confid' => 124, 'price' => 11400, 'unit' => '24 slices'),
      array('id' => 147, 'confid' => 134, 'price' => 13200, 'unit' => '24 slices'),
      array('id' => 148, 'confid' => 45, 'price' => 450, 'unit' => 'pce'),
      array('id' => 149, 'confid' => 63, 'price' => 350, 'unit' => 'pce'),
      array('id' => 150, 'confid' => 6, 'price' => 3900, 'unit' => '8 slices'),
      array('id' => 151, 'confid' => 28, 'price' => 4300, 'unit' => '8 slices'),
      array('id' => 152, 'confid' => 37, 'price' => 3900, 'unit' => '8 slices'),
      array('id' => 153, 'confid' => 52, 'price' => 5000, 'unit' => 'kg'),
      array('id' => 154, 'confid' => 61, 'price' => 4500, 'unit' => '8 slices'),
      array('id' => 155, 'confid' => 86, 'price' => 600, 'unit' => 'pce'),
      array('id' => 156, 'confid' => 6, 'price' => 7400, 'unit' => '16 slices'),
      array('id' => 157, 'confid' => 37, 'price' => 7400, 'unit' => '16 slices'),
      array('id' => 158, 'confid' => 11, 'price' => 490, 'unit' => 'pce'),
      array('id' => 159, 'confid' => 108, 'price' => 7400, 'unit' => '16 slices'),
      array('id' => 160, 'confid' => 35, 'price' => 9000, 'unit' => '16 slices'),
      array('id' => 161, 'confid' => 107, 'price' => 4500, 'unit' => '8 slices'),
      array('id' => 162, 'confid' => 6, 'price' => 11400, 'unit' => '24 slices'),
      array('id' => 163, 'confid' => 79, 'price' => 4000, 'unit' => 'kg'),
      array('id' => 164, 'confid' => 60, 'price' => 4300, 'unit' => '8 slices'),
      array('id' => 165, 'confid' => 21, 'price' => 5700, 'unit' => '8 slices'),
      array('id' => 166, 'confid' => 28, 'price' => 12100, 'unit' => '24 slices'),
      array('id' => 167, 'confid' => 15, 'price' => 5000, 'unit' => 'kg'),
      array('id' => 168, 'confid' => 21, 'price' => 5700, 'unit' => '8 slices'),
      array('id' => 169, 'confid' => 37, 'price' => 11400, 'unit' => '24 slices'),
      array('id' => 170, 'confid' => 74, 'price' => 11400, 'unit' => '24 slices'),
      array('id' => 171, 'confid' => 103, 'price' => 650, 'unit' => 'pce'),
      array('id' => 172, 'confid' => 43, 'price' => 4200, 'unit' => 'kg '),
      array('id' => 173, 'confid' => 12, 'price' => 3400, 'unit' => 'kg'),
      array('id' => 174, 'confid' => 27, 'price' => 5400, 'unit' => '8 slices'),
      array('id' => 175, 'confid' => 7, 'price' => 490, 'unit' => 'pce'),
      array('id' => 176, 'confid' => 84, 'price' => 5200, 'unit' => 'kg'),
      array('id' => 177, 'confid' => 115, 'price' => 3600, 'unit' => 'kg'),
      array('id' => 178, 'confid' => 51, 'price' => 4000, 'unit' => 'kg'),
      array('id' => 179, 'confid' => 118, 'price' => 450, 'unit' => 'pce'),
      array('id' => 180, 'confid' => 41, 'price' => 530, 'unit' => 'pce'),
      array('id' => 181, 'confid' => 135, 'price' => 400, 'unit' => 'pce'),
      array('id' => 182, 'confid' => 73, 'price' => 5400, 'unit' => '8 slices'),
      array('id' => 183, 'confid' => 10, 'price' => 8200, 'unit' => '16 slices'),
      array('id' => 184, 'confid' => 98, 'price' => 5400, 'unit' => '8 slices'),
      array('id' => 185, 'confid' => 113, 'price' => 850, 'unit' => 'pce'),
      array('id' => 186, 'confid' => 130, 'price' => 350, 'unit' => 'pce'),
      array('id' => 187, 'confid' => 39, 'price' => 4700, 'unit' => '8 slices'),
      array('id' => 188, 'confid' => 136, 'price' => 3400, 'unit' => 'kg'),
      array('id' => 189, 'confid' => 83, 'price' => 650, 'unit' => 'pce'),
      array('id' => 190, 'confid' => 91, 'price' => 800, 'unit' => '200 g'),
      array('id' => 191, 'confid' => 46, 'price' => 5200, 'unit' => 'kg'),
      array('id' => 192, 'confid' => 102, 'price' => 330, 'unit' => 'pce'),
      array('id' => 193, 'confid' => 95, 'price' => 10900, 'unit' => '16 slices'),
      array('id' => 194, 'confid' => 54, 'price' => 580, 'unit' => 'pce'),
      array('id' => 195, 'confid' => 57, 'price' => 530, 'unit' => 'pce'),
      array('id' => 196, 'confid' => 22, 'price' => 4700, 'unit' => '8 slices'),
      array('id' => 197, 'confid' => 92, 'price' => 450, 'unit' => 'pce'),
      array('id' => 198, 'confid' => 68, 'price' => 12400, 'unit' => '16 slices'),
      array('id' => 199, 'confid' => 42, 'price' => 5700, 'unit' => '8 slices'),
      array('id' => 200, 'confid' => 40, 'price' => 10900, 'unit' => '16 slices'),
      array('id' => 201, 'confid' => 9, 'price' => 450, 'unit' => 'pce'),
      array('id' => 202, 'confid' => 78, 'price' => 4200, 'unit' => 'kg'),
      array('id' => 203, 'confid' => 85, 'price' => 500, 'unit' => 'pce'),
      array('id' => 204, 'confid' => 137, 'price' => 600, 'unit' => 'pce'),
      array('id' => 205, 'confid' => 50, 'price' => 4900, 'unit' => '8 slices'),
      array('id' => 206, 'confid' => 38, 'price' => 12100, 'unit' => '24 slices'),
      array('id' => 207, 'confid' => 53, 'price' => 4200, 'unit' => 'kg'),
      array('id' => 208, 'confid' => 89, 'price' => 4700, 'unit' => '8 slices')
    );

    foreach ($prices as $price) {
      DB::table('prices')->insert($price);
    }
  }
}
